## 数据的标准化
* 最大最小标准化
* z分数标准化

## 数据的正则化
* 数据的正则化
* * 是将样本的某个范数缩放到单位1

## 特征选择
* 过滤式
* 包裹式
* 嵌入式


In [ ]:
import numpy as np
import sklearn

## 二元化

In [5]:
from sklearn.preprocessing import Binarizer

x= [[1,2,3,4,5],[5,4,3,2,1],[3,3,3,3,3],[1,1,1,1,1]]
binarizer = Binarizer(threshold=2.5)
binarizer.transform(x)

array([[0, 0, 1, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0]])

## 独热编码

In [9]:
from sklearn.preprocessing import OneHotEncoder
x= [[1,2,3,4,5],[5,4,3,2,1],[3,3,3,3,3],[1,1,1,1,1]]
encoder = OneHotEncoder(sparse=False)
encoder.fit(x)

F:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=False)

In [10]:
len(encoder.transform([[1,2,3,4,4]]))

array([[1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.]])

In [15]:
len(encoder.transform([[1,2,3,4,4]]).tolist()[0])

16

In [17]:
# 起始位置
encoder.feature_indices_

F:\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:100: DeprecationWarning: The ``feature_indices_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)


array([ 0,  6, 11, 15, 20, 26], dtype=int32)

## 数据的标准化

In [20]:
import sklearn
data = [[0,0],[0,0],[1,1],[1,1]]

In [25]:

scaler = sklearn.preprocessing.StandardScaler().fit(data)

In [27]:
scaler.transform([[0.5,0.2],[0.3,0.9]])

array([[ 0. , -0.6],
       [-0.4,  0.8]])

## 最大最小标准化

In [ ]:
min_max_scaler = sklearn.preprocessing.MinMaxScaler(feature_range=(0,1)).fit(data)


## 数据正则化

In [28]:
x = [[1,-1,2],[2,0,0],[0,1,-1]]

sklearn.preprocessing.normalize(x,norm='l2')

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])