In [1]:
import numpy as np
import sklearn

## 二元化

In [2]:
from sklearn.preprocessing import Binarizer
x = [[1, 2, 3, 4, 5],
    [5, 4, 3, 2, 1],
    [3, 3, 3, 3, 3],
    [1, 1, 1, 1, 1]]
binarizer = Binarizer(threshold=2.5)
binarizer.transform(x)

array([[0, 0, 1, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0]])

## 独热编码

In [3]:
from sklearn.preprocessing import OneHotEncoder
x = [[1, 2, 3, 4, 5],
    [5, 4, 3, 2, 1],
    [3, 3, 3, 3, 3],
    [1, 1, 1, 1, 1]]
encoder = OneHotEncoder(sparse=False)
encoder.fit(x)

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=False)

In [5]:
encoder.transform([[1, 2, 3, 4, 1]])

array([[1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0.]])

In [6]:
x1 = [[1, 2, 3, 4, 5],
    [2, 1, 3, 2, 1],
    [1, 1, 1, 3, 3],
    [1, 1, 1, 1, 1]]
encoder1 = OneHotEncoder(sparse=False)
encoder1.fit(x1)

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=False)

In [7]:
encoder1.transform([[1, 2, 3, 4, 1]])

array([[1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0.]])

In [8]:
encoder1.active_features_

array([ 1,  2,  4,  5,  7,  9, 11, 12, 13, 14, 16, 18, 20])

In [10]:
encoder1.feature_indices_

array([ 0,  3,  6, 10, 15, 21])

## 数据标准化

In [14]:
data = [[0,0],[0,0],[1,1],[1,1]]

In [15]:
scaler = sklearn.preprocessing.StandardScaler().fit(data)

In [ ]:
x = [[2, 3]]
scaler.transform(x)

## 最大最小标准化

In [ ]:
sklearn.preprocessing.MinMaxScaler(feature_range=(0,1)).fit(data)

## 正则化

In [16]:
x = [[1, -1, 2],
    [2, 0, 0],
    [0, 1, -1]]
sklearn.preprocessing.normalize(x, norm='l2')

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])