In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [4]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
15

15

In [8]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [9]:
a.T

array([[1, 3],
       [2, 4]])

## NumPy简介
* Numerical Python 是高性能科学计算和数据分析的基础语句
* ndarray,具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组

### ndarray
* N维数组对象（整个库的核心对象）
* xia

In [10]:
# 通过dtype指定数据类型
np.array([[1,2],[3,4]],dtype='str')

array([['1', '2'],
       ['3', '4']], dtype='<U1')

In [11]:
np.array([[1,2],[3,4]],dtype='float')

array([[1., 2.],
       [3., 4.]])

In [12]:
# ndmin指定维度
np.array([1,2,3,4,5],ndmin=2)

array([[1, 2, 3, 4, 5]])

In [13]:
a = np.array([1,2,3,4,5],ndmin=2)

In [14]:
a

array([[1, 2, 3, 4, 5]])

In [16]:
a.shape

(1, 5)

In [18]:
b = np.array([[1,2]])
b.shape

(1, 2)

In [20]:
# itemsize 分配每个元素所分配的字节的数量
b.itemsize

4

In [21]:
# dtype返回数据的类型
b.dtype

dtype('int32')

In [ ]:
# np.ndim : 返回数组的维数

In [22]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [23]:
a.shape

(5,)

In [32]:
a = np.array([1,2,3,4,5,6])
print(a.shape)
a.shape=(2,3)

(6,)


In [34]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a.shape=(3,2)

In [36]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
a.shape = (6,-1)

In [40]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [41]:
a.shape

(6, 1)

In [42]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [43]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [44]:
np.zeros((6,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [45]:
# np.empty()  未初始化开辟空间，速度快
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [46]:
np.empty(1)

array([0.])

In [47]:
np.empty((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [48]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [2]:
# 获取随机整数
import numpy as np
np.random.randint(3)


1

In [5]:
[ np.random.randint(3) for i in range(10)]

[2, 1, 2, 1, 1, 2, 1, 2, 1, 2]

In [7]:
np.random.random((2,2))

array([[0.7306627 , 0.2666752 ],
       [0.00381399, 0.26790649]])

In [8]:
np.random.randint(3,size=10)

array([1, 1, 2, 2, 0, 0, 1, 0, 2, 0])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [ ]:
np.linspace()

In [17]:
np.logspace(3,10,7,dtype='int')

array([       1000,       14677,      215443,     3162277,    46415888,
         681292069, -2147483648])

In [19]:
id(256)==id(256)

True

In [21]:
dic2 = {123:456}
dic2

{123: 456}

In [23]:
dic = {[1,2]:'ab'}
dic

TypeError: unhashable type: 'list'